version: '3'

services:
  nats-server:
    image: nats:latest
    ports: 
      - 8222:8222

  client-gateway:
    build: ./client-gateway
    ports: 
      - ${CLIENT_GATEWAY_PORT}:3000
    # volumes:
    #   - ./client-gateway/src:/usr/src/app/src
    develop: # Enables watch mode
      watch:
        - action: sync
          path: ./client-gateway/src
          target: /usr/src/app/src
          ignore:
            - node_modules
    command: npm run start:dev
    environment:
      - APP_PORT=3000
      - PRODUCTS_MICROSERVICE_HOST=localhost
      - PRODUCTS_MICROSERVICE_PORT=3001
      - ORDERS_MICROSERVICE_HOST=localhost
      - ORDERS_MICROSERVICE_PORT=3002
      - NATS_SERVERS=nats://nats-server:4222

  auth-ms:
    container_name: auth-ms
    build: ./auth-ms
    # volumes:
    #   - ./auth-ms/src:/usr/src/app/src
    develop:
      watch:
        - action: sync
          path: ./auth-ms/src
          target: /usr/src/app/src
          ignore:
            - node_modules
    command: npm run start:dev
    environment:
      - APP_PORT=3004
      - NATS_SERVERS=nats://nats-server:4222
      - DB_MONGO_URL=${DB_MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}

  products-ms:
    build: ./products-ms
    # volumes:
    #   - ./products-ms/src:/usr/src/app/src
    develop:
      watch:
        - action: sync
          path: ./products-ms/src
          target: /usr/src/app/src
          ignore:
            - node_modules
    command: npm run start:dev
    environment:
      - APP_PORT=3001
      - DATABASE_URL=file:./dev.db
      - NATS_SERVERS=nats://nats-server:4222

  orders-ms:
    depends_on:
      - orders-database
    build: ./orders-ms
    # volumes:
    #   - ./orders-ms/src:/usr/src/app/src
    develop:
      watch:
        - action: sync
          path: ./orders-ms/src
          target: /usr/src/app/src
          ignore:
            - node_modules
    command: npm run start:dev
    environment:
      - APP_PORT=3002
      - DATABASE_URL=postgresql://postgres:root@orders-database:5432/orders_ms_db?schema=public
      - NATS_SERVERS=nats://nats-server:4222

  orders-database:
    container_name: orders-database
    image: postgres:16.2
    restart: always
    volumes:
      - ./orders-ms/postgres:/var/lib/postgresql/data # Hacer Bind en un directorio local del pc para desarrollo
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  payments-ms:
    container_name: payments-ms
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    build: ./payments-ms
    # volumes:
    #   - ./payments-ms/src:/usr/src/app/src
    develop:
      watch:
        - action: sync
          path: ./payments-ms/src
          target: /usr/src/app/src
          ignore:
            - node_modules
    command: npm run start:dev
    environment:
      - APP_PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}