version: '3'

services:
  nats-server:
    image: nats:latest

  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: Dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/microservices-store-450002/microservices-registry/client-gateway
    ports: 
      - ${CLIENT_GATEWAY_PORT}:3000
    environment:
      - APP_PORT=3000
      - NATS_SERVERS=nats://nats-server:4222

  auth-ms:
    container_name: auth-ms
    build:
      context: ./auth-ms
      dockerfile: Dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/microservices-store-450002/microservices-registry/auth-ms
    environment:
      - APP_PORT=3004
      - NATS_SERVERS=nats://nats-server:4222
      - DB_MONGO_URL=${DB_MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}

  products-ms:
    build:
      context: ./products-ms
      dockerfile: Dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/microservices-store-450002/microservices-registry/products-ms
    environment:
      - APP_PORT=3001
      - DATABASE_URL=file:./dev.db
      - NATS_SERVERS=nats://nats-server:4222

  orders-ms:
    build:
      context: ./orders-ms
      dockerfile: Dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${DB_POSTGRES_URL}
    image: northamerica-south1-docker.pkg.dev/microservices-store-450002/microservices-registry/orders-ms
    environment:
      - APP_PORT=3002
      - DATABASE_URL=${DB_POSTGRES_URL}
      - NATS_SERVERS=nats://nats-server:4222

  payments-ms:
    container_name: payments-ms
    build:
      context: ./payments-ms
      dockerfile: Dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/microservices-store-450002/microservices-registry/payments-ms
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - APP_PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}